package reset

import (
	"bytes"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

func main() {
	root, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}

	pkgs, err := collectPackages(root)
	if err != nil {
		log.Fatal(err)
	}

	for _, pkg := range pkgs {
		structs := findResettableStructs(pkg)

		if len(structs) == 0 {
			continue
		}

		var buf bytes.Buffer

		err = fileTemplate.Execute(&buf, struct {
			PkgName string
			Meths   []string
		}{
			PkgName: pkg.Name,
			Meths:   generateMethodBodies(structs),
		})
		if err != nil {
			log.Fatalf("template execution error for package %s: %v", pkg.Name, err)
		}

		outPath := filepath.Join(pkg.Dir, "reset.gen.go")
		if err = os.WriteFile(outPath, buf.Bytes(), 0644); err != nil {
			log.Fatal(err)
		}
	}
}

var fileTemplate = template.Must(template.New("file").Parse(`// Code generated by cmd/reset; DO NOT EDIT.
package {{.PkgName}}

{{range .Meths}}{{.}}
{{end}}`))

var methodTemplate = template.Must(template.New("method").Parse(`
func (s *{{.StructName}}) Reset() {
	if s == nil { return }
{{- range .Fields }}
	{{.}}
{{- end }}
}
`))

func generateMethodBodies(structs []*structInfo) []string {
	var methods []string
	for _, st := range structs {
		methods = append(methods, renderMethod(st))
	}
	return methods
}

func renderMethod(st *structInfo) string {
	var buf bytes.Buffer
	err := methodTemplate.Execute(&buf, struct {
		StructName string
		Fields     []string
	}{
		StructName: st.Name,
		Fields:     genResetFieldLines(st),
	})
	if err != nil {
		log.Fatalf("failed to render method for %s: %v", st.Name, err)
	}
	return buf.String()
}

func genResetFieldLines(st *structInfo) []string {
	var lines []string
	for _, f := range st.Type.Fields.List {
		fieldType := exprToString(f.Type)
		for _, nameIdent := range f.Names {
			lines = append(lines, genResetFieldLine("s."+nameIdent.Name, fieldType))
		}
	}
	return lines
}

func genResetFieldLine(fieldName, typ string) string {
	switch typ {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"uintptr",
		"float32", "float64",
		"complex64", "complex128":
		return fieldName + " = 0"
	case "string":
		return fieldName + " = \"\""
	case "bool":
		return fieldName + " = false"

	default:
		if strings.HasPrefix(typ, "[") || strings.HasPrefix(typ, "[]") {
			return fieldName + " = " + fieldName + "[:0]"
		}
		if typ == "map[interface{}]interface{}" {
			return "clear(" + fieldName + ")"
		}
		if strings.HasPrefix(typ, "*") {
			base := strings.TrimPrefix(typ, "*")
			if isPrimitive(base) {
				return "if " + fieldName + " != nil { *" + fieldName + " = 0 }"
			}
			return "if r, ok := any(" + fieldName + ").(interface{ Reset() }); ok && " + fieldName + " != nil { r.Reset() }"
		}
		return "if r, ok := any(" + fieldName + ").(interface{ Reset() }); ok  { r.Reset() }"
	}
}

type packageInfo struct {
	Name string
	Dir  string
	ASTs []*ast.File
}

func collectPackages(root string) ([]*packageInfo, error) {
	var pkgs []*packageInfo
	fset := token.NewFileSet()

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() && strings.HasSuffix(info.Name(), ".go") && !strings.HasPrefix(info.Name(), "_") {
			if strings.Contains(path, "/vendor/") || strings.Contains(path, "/testdata/") {
				return nil
			}

			f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
			if err != nil {
				return err
			}

			var pkg *packageInfo
			for _, p := range pkgs {
				if filepath.Dir(path) == p.Dir {
					pkg = p
					break
				}
			}
			if pkg == nil {
				pkg = &packageInfo{
					Name: f.Name.Name,
					Dir:  filepath.Dir(path),
				}
				pkgs = append(pkgs, pkg)
			}
			pkg.ASTs = append(pkg.ASTs, f)
		}
		return nil
	})
	return pkgs, err
}

type structInfo struct {
	Name string
	Type *ast.StructType
}

func findResettableStructs(pkg *packageInfo) []*structInfo {
	var res []*structInfo

	for _, f := range pkg.ASTs {
		for _, decl := range f.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			comment := ""
			if genDecl.Doc != nil && len(genDecl.Doc.List) > 0 {
				comment = strings.TrimSpace(genDecl.Doc.Text())
			}

			if !strings.Contains(comment, "generate:reset") {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}

				res = append(res, &structInfo{
					Name: typeSpec.Name.Name,
					Type: structType,
				})
			}
		}
	}
	return res
}

func exprToString(expr ast.Expr) string {
	var b strings.Builder
	if err := format.Node(&b, token.NewFileSet(), expr); err != nil {
		return ""
	}
	return b.String()
}

var primitives = map[string]bool{
	"int":        true,
	"int8":       true,
	"int16":      true,
	"int32":      true,
	"int64":      true,
	"uint":       true,
	"uint8":      true,
	"uint16":     true,
	"uint32":     true,
	"uint64":     true,
	"uintptr":    true,
	"float32":    true,
	"float64":    true,
	"complex64":  true,
	"complex128": true,
	"string":     true,
	"bool":       true,
}

func isPrimitive(typ string) bool {
	return primitives[typ]
}
