package reset

import "text/template"

var fileTemplate = template.Must(template.New("file").Parse(`// Code generated by cmd/reset; DO NOT EDIT.
package {{.Name}}

{{range .Funcs}}{{.}}
{{end}}`))

var methodTemplate = template.Must(template.New("method").Parse(`
func (s *{{.Name}}) Reset() {
	if s == nil { return }
{{- range .Fields }}
	{{.}}
{{- end }}
}
`))
